# Generated by Django 5.1 on 2024-09-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_airbuds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('origina_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('delivery', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Refridgerators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('origina_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('delivery', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tvs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('origina_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('delivery', models.CharField(max_length=200)),
            ],
        ),
    ]
