# Generated by Django 5.1 on 2024-09-12 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_phones_refridgerators_tvs'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='laptop_image/')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.laptops')),
            ],
        ),
    ]
