# Generated by Django 5.1 on 2024-09-12 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_laptopimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirbudImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='airbuds_image/')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.airbuds')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='phones_image/')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.phones')),
            ],
        ),
        migrations.CreateModel(
            name='RefridgeratorImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='refridgerator_image/')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.refridgerators')),
            ],
        ),
        migrations.CreateModel(
            name='TvImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tvs_image/')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.tvs')),
            ],
        ),
    ]
