# Generated by Django 5.1 on 2024-09-13 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_airbudimages_phoneimages_refridgeratorimages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptopimages',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='phoneimages',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='refridgeratorimages',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='tvimages',
            name='product_name',
        ),
        migrations.DeleteModel(
            name='AirbudImages',
        ),
        migrations.DeleteModel(
            name='Airbuds',
        ),
        migrations.DeleteModel(
            name='LaptopImages',
        ),
        migrations.DeleteModel(
            name='Laptops',
        ),
        migrations.DeleteModel(
            name='PhoneImages',
        ),
        migrations.DeleteModel(
            name='Phones',
        ),
        migrations.DeleteModel(
            name='RefridgeratorImages',
        ),
        migrations.DeleteModel(
            name='Refridgerators',
        ),
        migrations.DeleteModel(
            name='TvImages',
        ),
        migrations.DeleteModel(
            name='Tvs',
        ),
    ]
