# Generated by Django 5.1 on 2024-09-13 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_remove_laptopimages_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airbuds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('original_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('Connectivity_Technology', models.CharField(max_length=50)),
                ('delivery_date', models.DateField()),
                ('model_name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sname', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('discount', models.IntegerField()),
                ('original_price', models.IntegerField()),
                ('model_name', models.CharField(max_length=100)),
                ('screen_size', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('RAM', models.IntegerField()),
                ('url', models.CharField(max_length=100)),
                ('delivery_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('original_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('Operating_System', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Refridgerators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('original_price', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('configuration', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('delivery_date', models.DateField()),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tvs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('original_price', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('screen_size', models.FloatField()),
                ('discount', models.IntegerField()),
                ('delivery_date', models.DateField()),
                ('Resolution', models.IntegerField()),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AirbudImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='airbuds_image/')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.airbuds')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='laptop_image/')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.laptops')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='phones_image/')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.phones')),
            ],
        ),
        migrations.CreateModel(
            name='RefridgeratorImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='refridgerator_image/')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.refridgerators')),
            ],
        ),
        migrations.CreateModel(
            name='TvImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tvs_image/')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.tvs')),
            ],
        ),
    ]
